
export const Types = {
    SIGN_IN:  'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    HISTORY: 'HISTORY',
    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',
    RESTORE: 'RESTORE',
    REMOVE: 'REMOVE',
    CLEAR:'CLEAR',
    SETTINGS:'SETTINGS',
    SEARCH: 'SEARCH',
    FETCH_DOG: 'FETCH_DOG',
    FETCH_BREED: 'FETCH_BREED',
    FETCH_BREEDS: 'FETCH_BREEDS',
    FETCHING: 'FETCHING',
    FETCHED: 'FETCHED',
    VIEW: 'VIEW',
    SHOW_MESSAGE:'SHOW_MESSAGE'
}

export const SagaTypes = {
    SAGA_SIGN_IN:  'SAGA_SIGN_IN',
    SAGA_SIGN_OUT: 'SAGA_SIGN_OUT',
    SAGA_AUTHENTICATE_USER: 'SAGA_AUTHENTICATE_USER',
    SAGA_FORWARD_ROUTE: 'SAGA_FORWARD_ROUTE',
    SAGA_ADD_FAVORITE: 'SAGA_ADD_FAVORITE',
    SAGA_REMOVE_FAVORITE: 'SAGA_REMOVE_FAVORITE',
    SAGA_SEARCH: 'SAGA_SEARCH',
    SAGA_FETCH_DOG: 'SAGA_FETCH_DOG',
    SAGA_FETCH_BREED: 'SAGA_FETCH_BREED',
    SAGA_FETCH_BREEDS: 'SAGA_FETCH_BREEDS',
}